/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_actions_voicebletest_jni_DecodeJni */

#ifndef _Included_com_actions_voicebletest_jni_DecodeJni
#define _Included_com_actions_voicebletest_jni_DecodeJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_actions_voicebletest_jni_DecodeJni
 * Method:    decodeInit
 * Signature: ()V
 */
JNIEXPORT jshort JNICALL Java_com_actions_voicebletest_jni_DecodeJni_decodeInit
  (JNIEnv *, jobject, jshort);

/*
 * Class:     com_actions_voicebletest_jni_DecodeJni
 * Method:    Decode
 * Signature: ([I)[I
 */
JNIEXPORT jshortArray JNICALL Java_com_actions_voicebletest_jni_DecodeJni_Decode
  (JNIEnv *, jobject, jshortArray, jshort, jshort);

JNIEXPORT jshort JNICALL Java_com_actions_voicebletest_jni_DecodeJni_decodeInitTest
    (JNIEnv *, jobject, jshort);

JNIEXPORT jshortArray JNICALL Java_com_actions_voicebletest_jni_DecodeJni_DecodeTest
      (JNIEnv *, jobject, jshortArray, jshort, jshort);

#ifdef __cplusplus
}
#endif
#endif
